### ISSUE TITLE
Release example firmware compiled .hex files

### ISSUE THREAD

**Issue by 0x0f0f0f** [AnthonyDiGirolamo/teensy-thumb-keyboard#1]
on linux the arduino IDE & teensyduino are quite bulky and packages are not available on many distributions, plus, i've already soldered my teensy to the board.

could you please release a compiled example firmware .hex file for the standard USB US keyboard behavior?  `teensy_loader_cli` is easier to build and install rather than the whole arduino ide

**Comment by AnthonyDiGirolamo** [comment]
Good idea! I'll get hex files for the teensy 3.2 and LC added soon.

**Comment by AnthonyDiGirolamo** [comment]
Finally got around to uploading these. See: https://github.com/AnthonyDiGirolamo/teensy-thumb-keyboard#uploading-the-firmware-without-compiling
